# Generated by Django 3.1.5 on 2021-01-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='posts',
            field=models.ManyToManyField(to='post.Post'),
        ),
    ]
