# Generated by Django 3.1.5 on 2021-01-28 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20210128_0448'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
