# Generated by Django 3.1.5 on 2021-01-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0004_peoplelist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PeopleList',
        ),
    ]
